version: "3.8"
services:
  vault-server:
    image: vault:latest
    ports:
      - "8200:8200"
      - "8201:8201"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "root_token"
    cap_add:
      - IPC_LOCK